repository:
    description: "Solutions of Advent Of Code 2022"
    topics: advent-of-code,advent-of-code-2022,advent-of-code-2022-php
    has_downloads: false
    has_issues: false
    has_pages: false
    has_projects: false
    has_wiki: false
    name: aoc2022
    private: false
